### ISSUE TITLE
Radius of inscribed circle?

### ISSUE THREAD

**Issue by ornamentist** [PieceMaker/max-inscribed-circle#12]
Hi,

I might be missing something obvious here but is there a way to access the radius of the inscribed circle (as well as the center)?  This is very useful for making full use of the inscribed circle space.

**Comment by PieceMaker** [comment]
The object returned from calling `maxCircle` is a GeoJSON point geometry representing the approximate center you are referring to. Currently the radius is not returned, but it would not be hard, perhaps shoving that in the `properties` of the object. I'll try to take a look at this in the next few days.

**Comment by ornamentist** [comment]
Many thanks, this is already a very handy library, adding the radius would make it more so.

**Comment by PieceMaker** [comment]
Sorry it took me two years to get around to this!
