### ISSUE TITLE
Convert Lodash Calls to JavaScript Array Methods

### ISSUE THREAD

**Issue by PieceMaker** [PieceMaker/max-inscribed-circle#23]
Inside the method `GeoJSONUtils.fixMultiPoly`, there are three Lodash functions that are being used: `indexOf`, `map`, and `max`. First, this library previously removed Lodash as a dependency so these should no longer work. However, it looks like a different module is pulling it in as a dependency and this is saving us.

Second, there is no reason to use Lodash for these as equivalent methods exist on native JavaScript arrays.

Replace `_.indexOf` with `Array.indexOf`, `_.map` with `Array.map`, and `_.max` with `Math.max`.

**Comment by mohcinemoussa** [comment]
I will look into this.

**Comment by PieceMaker** [comment]
Great! Assigned.

**Comment by PieceMaker** [comment]
Closed with #29.
