### ISSUE TITLE
Create More In-Depth User Guide

### ISSUE THREAD

**Issue by PieceMaker** [PieceMaker/max-inscribed-circle#25]
Although this repository's README contains a lot of information on this library, it does not fully demonstrate how some of the options work or a few more of the internals. Additionally, visual examples might make it easier for people to understand the the goal of this library.

A user guide should cover the following:

- [x] All three options parameters
    - [x] `decimalPlaces` - The reason for this should be explained in more depth and it needs to demonstrate how changing this value can affect the output, both showing raw output and possibly graphically.
    - [x] `numSegments` - It needs to be explained how as this value is increased the Voronoi starts to converge to the medial axis and therefore the resulting point estimate gets closer and closer to the actual desired center. Several visual examples should be provided for this. It also needs to be explained that as this value increases so does the computation time. Providing runtimes with the visual examples would be useful.
    - [x] `units` - The different units should be quickly touched over and all shown with raw output. It also needs to be explained that these units do not change anything about the input. The input is _always_ expected to be `(lat, lon)` coordinates regardless of the value of `units`.
- [x] It needs to be explained that any extra properties that are defined on the input will be returned in the output. Provide a raw output example of this.
- [x] It is not explained in the README that the MultiPolygon geometry type is handled by this library. A section needs to explain how the `GeoJSONUtils.fixMultiPoly` utility returns the Polygon of largest area and computes the max-inscribed circle over this polygon. One or two visual examples would be helpful.
- [ ] It needs to be explained a little more that the centroid is always checked to see if it is the best estimate of the max-inscribed circle centroid. It needs to be covered that this will be returned whenever the Voronoi calculation does not return, as well as when the centroid is closer to the true shape center than all the Voronoi-approximated points.
- [ ] Perhaps go over the ES6 usage a little more. Give some sample run-code similar to the `npm run test` script.

**Comment by Morgul** [comment]
@PieceMaker As part of this effort, it would be useful to generate the example polygons to demonstrate some of these points (like the multipolygon example). Having the example geometries will expedite the process, I think.

**Comment by PieceMaker** [comment]
There are multiple (basic) example polygons in `test/max-inscribed-circle.spec.js`. I can work on generating a few more over the weekend.

**Comment by raedeanne** [comment]
I am slowly navigating the iPad browser GitHub UX.

**Comment by PieceMaker** [comment]
I'm having trouble getting runkit.com to work with ES6 modules so I'm just going to put the sample code an results here (for now).

<details>

<summary>Example for decimalPlaces</summary>

```javascript
// Input
import maxInscribedCircle from 'max-inscribed-circle';
const polygon = {
    "type": "Feature",
    "geometry": {
        "type": "Polygon",
        "coordinates": [[
            [0.0,0.0],
            [1.0,0.0],
            [1.0,3.0],
            [2.0,3.0],
            [2.0,0.0],
            [3.0,0.0],
            [3.0,4.0],
            [0.0,4.0],
            [0.0,0.0]
        ]]
    }
};

maxInscribedCircle(polygon);
maxInscribedCircle(polygon, {decimalPlaces: 1e-5});
```

```javascript
// Output with default parameters
{
  type: 'Feature',
  geometry: { type: 'Point', coordinates: [ 1.25, 3.5 ] },
  properties: { radius: 0.4994165362629234, units: 'degrees' }
}
```

```javascript
// Output with decimalPlaces set to 1e-5
{
  type: 'Feature',
  geometry: { type: 'Point', coordinates: [ 1.7499950000000002, 3.499995 ] },
  properties: { radius: 0.4994115420975617, units: 'degrees' }
}
```
</details>

<details>

<summary>Example for numSegments</summary>

```javascript
import maxInscribedCircle from '../max-inscribed-circle.js';
const polygon = {
    "type": "Feature",
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    49.0138,
                    15
                ],
                [
                    49.0138,
                    15.0167
                ],
                [
                    49.0153,
                    15.0167
                ],
                [
                    49.0138,
                    15
                ]
            ]
        ]
    }
};

maxInscribedCircle(polygon);
maxInscribedCircle(polygon, {numSegments: 10});
maxInscribedCircle(polygon, {numSegments: 100});
```

```javascript
// Output with numSegments 2
{
  type: 'Feature',
  geometry: { type: 'Point', coordinates: [ 49.014175, 15.012525 ] },
  properties: { radius: 0.0003617784458710126, units: 'degrees' }
}
// Execution time: 1ms
```

```javascript
// Output with numSegments 10
{
  type: 'Feature',
  geometry: {
    type: 'Point',
    coordinates: [ 49.014475000000004, 15.015730269461077 ]
  },
  properties: { radius: 0.0006511913547888886, units: 'degrees' }
}
// Execution time: 7ms
```

```javascript
// Output with numSegments 100
{
  type: 'Feature',
  geometry: {
    type: 'Point',
    coordinates: [ 49.01451640809969, 15.015981847557223 ]
  },
  properties: { radius: 0.0006911268856890232, units: 'degrees' }
}
// Execution time: 28ms
```

</details>

<details>

<summary>Example for units</summary>

```javascript
import maxInscribedCircle from '../max-inscribed-circle.js';
const polygon = {
    "type": "Feature",
    "geometry": {
        "type": "Polygon",
        "coordinates": [[
            [0.0,0.0],
            [1.0,0.0],
            [1.0,3.0],
            [2.0,3.0],
            [2.0,0.0],
            [3.0,0.0],
            [3.0,4.0],
            [0.0,4.0],
            [0.0,0.0]
        ]]
    }
};

console.log(maxInscribedCircle(polygon));
console.log(maxInscribedCircle(polygon, {units: "radians"}));
console.log(maxInscribedCircle(polygon, {units: "miles"}));
console.log(maxInscribedCircle(polygon, {units: "kilometers"}));
```

```javascript
// Output with units "degrees"
{
  type: 'Feature',
  geometry: { type: 'Point', coordinates: [ 1.25, 3.5 ] },
  properties: { radius: 0.4994165362629234, units: 'degrees' }
}
```

```javascript
// Output with units "radians"
{
  type: 'Feature',
  geometry: { type: 'Point', coordinates: [ 1.25, 3.5 ] },
  properties: { radius: 0.008726647167630651, units: 'radians' }
}
```

```javascript
// Output with units "miles"
{
  type: 'Feature',
  geometry: { type: 'Point', coordinates: [ 1.25, 3.5 ] },
  properties: { radius: 34.546713381023544, units: 'miles' }
}
```

```javascript
// Output with units "kilometers"
{
  type: 'Feature',
  geometry: { type: 'Point', coordinates: [ 1.25, 3.5 ] },
  properties: { radius: 55.59754589946995, units: 'kilometers' }
}
```

</details>
