### ISSUE TITLE
Voronoi Close Cells Error

### ISSUE THREAD

**Issue by wassfila** [PieceMaker/max-inscribed-circle#32]
Hi @PieceMaker ,
regarding this error you mention on your readme, I suggest that you have a look at this very similar issue
https://github.com/gorhill/Javascript-Voronoi/issues/27#issuecomment-612588509
that I solved by adjusting the epsilon paramter, I don't say this will definitely solve your issue but it's worth the try.

**Comment by PieceMaker** [comment]
Thanks for the heads up! I believe the epsilon parameter was discussed in https://github.com/gorhill/Javascript-Voronoi/issues/15 as well. In that issue it looked like the choice of epsilon that caused the calculation to succeed was still dependent on the input sites. Additionally, I was reluctant to write code that redefined parts of the Voronoi prototype. Therefore I decided to expose my own version of epsilon in the form of `options.decimalPlaces` and leave it to the user's discretion whether to employ it and at what value.

**Comment by wassfila** [comment]
That's a nice way out
